### ISSUE TITLE
Window buttons/ Aplication theme not working

### ISSUE THREAD

**Issue by j-dominguez9** [NicklasVraa/NovaOS-nord-Theme#1]
I recently downloaded your amazing theme on linux mint as well, but when choosing the theme for the Applications setting, I feel like something went wrong, since it looks very different from the images in the repo. The color of some windows is black and the window cannot be moved, and some look fine (firefox ss) but they are still missing missing the min, max, and close buttons as well. (screenshots attached)

![2022-09-22_17-53](https://user-images.githubusercontent.com/83036592/191858383-ca0abe0c-4c34-43ea-99af-e10c9e890dd4.png)
![2022-09-22_17-52](https://user-images.githubusercontent.com/83036592/191858401-69e08923-06e5-4b58-bdf7-52a5529d1ad7.png)
![image](https://user-images.githubusercontent.com/83036592/191858812-0bb83750-6554-4dbf-95db-0b14e6e61993.png)

**Comment by NicklasVraa** [comment]
Hey Joaquin

Thank you for the kind words :)
I only tested it on Mint 20, since that's what I'm using. I know that Mint
21 removed metacity support, which controls the window decoration, i.e. the
close/min/max buttons, so that is most likely the problem. You are more
than welcome to fork and alter the files. I would suggest that you view my
theme as a reference and alter one of the existing themes for Mint 21 until
it works for you. I will also have a look at it, when I have some time for
it :)

Best regards
Nicklas

**Comment by NicklasVraa** [comment]
I've recently tested it on Mint 21, and it works as expected for me. There are no window borders by default, because I added them through metacity, but otherwise it looks the same :)
